{% set version = "1.10.10" %}
{% set sha256 = "8149b30eabbc9a2af5f038fb2b7f91070d4e01266377e0cd12e3af3feda93f8f" %}

package:
  name: thrust
  version: {{ version }}

source:
  url: https://github.com/thrust/thrust/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: mkdir -p "$PREFIX"/include && cp -r thrust "$PREFIX"/include  # [not win]

requirements:
  run:
    - cub {{ version }}.*

test:
  commands:
    - test -e "$PREFIX"/include/thrust/version.h  # [not win]
    - if not exist "%LIBRARY_INC%"\thrust\version.h exit 1  # [win]

about:
  home: https://github.com/thrust/thrust
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Thrust is a C++ parallel programming library which resembles the C++ Standard Library.
  description: |
    Thrust's high-level interface greatly enhances programmer productivity while enabling
    performance portability between GPUs and multicore CPUs. Interoperability with established
    technologies (such as CUDA, TBB, and OpenMP) facilitates integration with existing software.
    Develop high-performance applications rapidly with Thrust!
  doc_url: https://thrust.github.io/
  dev_url: https://github.com/thrust/thrust

extra:
  recipe-maintainers:
    - rongou
    - kkraus
